BEGIN;

CREATE TABLE IF NOT EXISTS films (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE,
    year INTEGER,
    director TEXT,
    genre_id INTEGER REFERENCES genres(id),
    photo BYTEA
    CHECK (year > (0))
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    genre_name TEXT UNIQUE NOT NULL
);

-- CREATE TABLE IF NOT EXISTS photos (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     photo VARBINARY(255),
--     film_id INTEGER REFERENCES films(id),
--     user_id INTEGER REFERENCES users(id)
-- );

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE,
    hash TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

COMMIT;