PRAGMA foreign_keys = ON;

BEGIN;

CREATE TABLE IF NOT EXISTS film (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE,
    year DATETIME NOT NULL,
    director TEXT UNIQUE,
    genre_id INTEGER REFERENCES genre(id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS photo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    photo IMAGE,
    film_id INTEGER REFERENCES film(id),
    user_id INTEGER REFERENCES users(id)
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

COMMIT;